import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import {useEffect, useState} from "react";
import {checkLogin} from "@/pages/checkLogin";
const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [auth_info,setAuthInfo] = useState({
        route:'/login',
        text:'Đăng nhập',
    });
    useEffect(() => {

        const auth_check = checkLogin();
        auth_check.then(res => {
            if (res) {
                setAuthInfo({
                    route: '/logout',
                    text:'Đăng xuất'
                })
            }
        })
    },[])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                    <div className={styles.thirteen}>
                        <Image
                            src="/thirteen.svg"
                            alt="13"
                            width={40}
                            height={31}
                            priority
                        />
                    </div>
                </div>

                <div className="d-flex">
                    <Link
                        className={styles.card}
                        href={auth_info.route}
                    >
                        <h2 className={inter.className}>
                            {auth_info.text}
                        </h2>
                        <p className={inter.className}>
                            Xác thực người dùng
                        </p>
                    </Link>

                    <Link
                        className={styles.card}
                        href="/dashboard"
                    >
                        <h2 className={inter.className}>
                            Dashboard
                        </h2>
                        <p className={inter.className}>
                            Trang tổng quát
                        </p>
                    </Link>
                </div>
            </main>
        </>
    )
}
